# This is a basic workflow to help you get started with Actions

name: SGSI_Build

on:
  watch:
    types: [started]
    
env:              
  ROM_URL: 'https://media-gdgz-person.gdoss.xstore.ctyun.cn/PERSONCLOUD/0cfd64f9-558f-4023-96b3-e7294c01a36d.zip?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=B12spNbFIkHcJjk5MvKN&x-amz-UID=810369093&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22Sky_Mi8_12.5.1Stable_10%2889A09722AA%29.zip%22&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D10240%2Cconcurrency%3D10&Signature=LxBmQHRL7QV5McBc0wXVY52eC2c%3D&x-amz-SHID=114461615160&Expires=1624509212&x-amz-FSIZE=2123511888&x-amz-UFID=31411113499928292'
  ZIP_NAME: 'Sky_Mi8_12.5.1Stable_10(89A09722AA).zip'
  OS_TYPE: 'MIUI'
  BUILD_TYPE: 'ab'
  REPACK_NAME: 'SGSI.zip'
  VERSION: '10'
  upload_WeTransfer: 'true'
  upload_action-gh-release: 'false'
  SETUP: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: Clean Up
         run: |       
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
           df -h
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git wget git zip unzip curl axel

       - name: Cloning...
         run: |
             git clone https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool
           
       - name: Download zip...
         run: |
            cd $GITHUB_WORKSPACE/SGSI-build-tool
            mkdir ./tmp
            axel -n $(nproc) -U "Mozilla/5.0" $ROM_URL -o "$GITHUB_WORKSPACE/SGSI-build-tool/tmp/$ZIP_NAME" || wget -U "Mozilla/5.0" $ROM_URL -O "$GITHUB_WORKSPACE/SGSI-build-tool/tmp/$ZIP_NAME"
            echo "zip_file: $(ls "$GITHUB_WORKSPACE/SGSI-build-tool/tmp/")"
            
       - name: Setup Tool Utils...
         if: env.SETUP == 'true'
         run: |
            sudo sed -i 's/USE_MIRROR_FOR_PIP\=true/USE_MIRROR_FOR_PIP\=false/' $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
            sudo apt-get -y --purge remove "adoptopenjdk-11-hotspot"
            java -version
            
       - name: Building AB DEVICES SGSI...
         if: env.BUILD_TYPE == 'AB' || env.BUILD_TYPE == 'ab'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --AB $OS_TYPE $ZIP_NAME --fix-bug

       - name: Building A-only DEVICES SGSI...
         if: env.BUILD_TYPE == 'a-only'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --a-only $OS_TYPE $ZIP_NAME --fix-bug     

       - name: Repack output file ...
         run: |            
             cd $GITHUB_WORKSPACE/SGSI-build-tool
             pwd
             zip -r $REPACK_NAME ./SGSI/*
             ls "$REPACK_NAME"

       - name: Upload SGSI to WeTransfer...
         if: env.upload_WeTransfer == 'true' 
         run: |
           cd $GITHUB_WORKSPACE/SGSI-build-tool
           pwd
           ls "$REPACK_NAME"
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ./$REPACK_NAME

       - name: Upload SGSI to action-gh-release...
         if: env.upload_action-gh-release == 'true'
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ github.workspace }}/SGSI-build-tool/${{ env.REPACK_NAME }}
           name: xiaoxinSGSI-${{ env.OS_TYPE }}-${{ env.BUILD_TYPE }}-Android${{ env.VERSION }}-unpack
           tag_name: 12
           #body: Use actions auto bulid
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           
